// <auto-generated />
#nullable disable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace InstanceManager.Application.Core.Data.Migrations
{
    [DbContext(typeof(InstanceManagerDbContext))]
    [Migration("20251109202902_allowed_identity_ids")]
    partial class allowed_identity_ids
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("InstanceManager.Application.Core.Modules.DataSet.DataSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedIdentityIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataSets");
                });

            modelBuilder.Entity("InstanceManager.Application.Core.Modules.DataSet.DataSetInclude", b =>
                {
                    b.Property<Guid>("ParentDataSetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IncludedDataSetId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParentDataSetId", "IncludedDataSetId");

                    b.HasIndex("IncludedDataSetId");

                    b.HasIndex("ParentDataSetId", "IncludedDataSetId")
                        .IsUnique();

                    b.ToTable("DataSetInclude");
                });

            modelBuilder.Entity("InstanceManager.Application.Core.Modules.ProjectInstance.ProjectInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MainHost")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentProjectId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentProjectId");

                    b.ToTable("ProjectInstances");
                });

            modelBuilder.Entity("InstanceManager.Application.Core.Modules.Translations.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CultureName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DataSetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalGroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CultureName");

                    b.HasIndex("DataSetId");

                    b.HasIndex("InternalGroupName", "ResourceName", "CultureName");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("InstanceManager.Application.Core.Modules.DataSet.DataSetInclude", b =>
                {
                    b.HasOne("InstanceManager.Application.Core.Modules.DataSet.DataSet", "IncludedDataSet")
                        .WithMany("IncludedIn")
                        .HasForeignKey("IncludedDataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstanceManager.Application.Core.Modules.DataSet.DataSet", "ParentDataSet")
                        .WithMany("Includes")
                        .HasForeignKey("ParentDataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncludedDataSet");

                    b.Navigation("ParentDataSet");
                });

            modelBuilder.Entity("InstanceManager.Application.Core.Modules.ProjectInstance.ProjectInstance", b =>
                {
                    b.HasOne("InstanceManager.Application.Core.Modules.ProjectInstance.ProjectInstance", "ParentProject")
                        .WithMany("ChildProjects")
                        .HasForeignKey("ParentProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentProject");
                });

            modelBuilder.Entity("InstanceManager.Application.Core.Modules.Translations.Translation", b =>
                {
                    b.HasOne("InstanceManager.Application.Core.Modules.DataSet.DataSet", "DataSet")
                        .WithMany()
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DataSet");
                });

            modelBuilder.Entity("InstanceManager.Application.Core.Modules.DataSet.DataSet", b =>
                {
                    b.Navigation("IncludedIn");

                    b.Navigation("Includes");
                });

            modelBuilder.Entity("InstanceManager.Application.Core.Modules.ProjectInstance.ProjectInstance", b =>
                {
                    b.Navigation("ChildProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
